#!/bin/sh
cp torrc config
if [ "$TOR_ADDRESS" != "" ]; then
	echo >> config "Address $TOR_ADDRESS"
fi
if [ "$BW" != "" ]; then
	echo >> config "BandwidthRate $BW"
fi
if [ "$BWB" != "" ]; then
	echo >> config "BandwidthBurst $BW"
fi
if [ "$RBW" != "" ]; then
	echo >> config "RelayBandwidthRate $RBW"
fi
if [ "$RBWB" != "" ]; then
	echo >> config "RelayBandwidthBurst $RBWB"
fi
cat config
echo "------------------------"
tor -f ./config
