#!/bin/sh
cp torrc config
if [ "$TOR_ADDRESS" != "" ]; then
	echo >> config "Address $TOR_ADDRESS"
fi
if [ "$TOR_NAME" != "" ]; then
        # Set the server’s nickname to 'name'. Nicknames must be between 1 and 19 characters inclusive, and must contain only the characters [a-zA-Z0-9]. If not set, Unnamed will be used. Relays can always be uniquely identified by their identity fingerprints. 
	echo >> config "Nickname $TOR_NAME"
fi
if [ "$TOR_EMAIL" != "" ]; then
	# Administrative contact information for this relay or bridge. This line can be used to contact you if your relay or bridge is misconfigured or something else goes wrong. Note that we archive and publish all descriptors containing these lines and that Google indexes them, so spammers might also collect them. You may want to obscure the fact that it’s an email address and/or generate a new address for this purpose.
	echo >> config "ContactInfo $TOR_EMAIL"
fi
if [ "$BW" != "" ]; then
	echo >> config "BandwidthRate $BW"
fi
if [ "$BWB" != "" ]; then
	echo >> config "BandwidthBurst $BW"
fi
if [ "$RBW" != "" ]; then
	echo >> config "RelayBandwidthRate $RBW"
fi
if [ "$RBWB" != "" ]; then
	echo >> config "RelayBandwidthBurst $RBWB"
fi
cat config
echo "------------------------"
tor -f ./config
